### ISSUE TITLE
Create NFT badge iteration on program

### ISSUE THREAD

**Issue by jpcaulfi** [PrestigeDAO/prestige-program#2]
Add functionality to our on-chain program to support management of badge NFTs.

We can figure out the details, but in a simple sense, when a user gets to N balance of XP tokens, they are automatically minted a badge. 

We can also have special niche badges for certain project types.

**Comment by valentinmadrid** [comment]
> We can figure out the details, but in a simple sense, when a user gets to N balance of XP tokens, they are automatically minted a badge.

Are you considering using an SPL Token as XP or just an integer associated to a certain account stored on chain?

**Comment by jpcaulfi** [comment]
I was thinking we create an SPL token and every time someone earns XP we mint to their account

**Comment by valentinmadrid** [comment]
That would be a great idea, my only concern is that a Token should be non transferable. 
Could we make that possible with the Token Program?

**Comment by jpcaulfi** [comment]
re: non-transferable: 
Yes, the tokens would have to be frozen automatically after mint. 

re: DAO decision-making:
This is surely a possibility. It might be the better way to go!
