### ISSUE TITLE
Create developer wallet support on program

### ISSUE THREAD

**Issue by jpcaulfi** [PrestigeDAO/prestige-program#3]
We might just want to consider the fact that in order for the XP token balance tracking to work properly, someone will have to use the same wallet. 

They'll also have to somehow link it to their GitHub profile...

**Comment by cdhiraj40** [comment]
> We might just want to consider the fact that in order for the XP token balance tracking to work properly, someone will have to use the same wallet.
> They'll also have to somehow link it to their GitHub profile...

Do you mean connecting wallet + GH profile?
maybe we can have a `user_info` account that gets init the first time the user uses the platform(first time doing tsx).
The way we initialize the account is by connecting their GH user-id + wallet pubkey as seeds.
```
    seeds = [b"user", author.github_id.to_bytes().as_ref(), author.key().to_bytes().as_ref()],
```
- Reason to choose `github_user_id` and not `username` because a person may change their username later but their ID stays the same.

- Then we can fetch the person's account/info any time by using seeds and update the XP anytime just the same. 

Do let me know what you think about this. I am not sure about any other constraints to the user.

**Comment by jpcaulfi** [comment]
I think this is perfect!   
   
I'd say the only edge case to consider is what if someone wants to change the wallet they've been using for some time. 
(ie. they lose their private key lol)   
   
Do we provide a way for someone to recover their XP (ie. transfer it to their new wallet)? And how can this not be gamed?

**Comment by cdhiraj40** [comment]
> I think this is perfect!
> 
> I'd say the only edge case to consider is what if someone wants to change the wallet they've been using for some time. (ie. they lose their private key lol)
> 
> Do we provide a way for someone to recover their XP (ie. transfer it to their new wallet)? And how can this not be gamed?

Well, this is a really good question. But I think there is a way to recover if the user loses private data that is proving dao that the `github_user_id` we have is the same as the GH account user uses. 
But not sure about how to just transfer old XPs to a new wallet. Maybe an admin account(DAO) may help in that which gives power to admin(DAO) and only admin(DAO) to transfer/increment XP of the user.

This can be easily done by having an account with an admin/dao public key stored in it and then validating if the admin is the one who is transferring the XP or incrementing it. This account will be again a PDA with a pretty normal seed which can ehave has a count for the number of students that may be useful to show student stats later 😉

**Comment by cdhiraj40** [comment]
@jpcaulfi As discussed earlier, I would like to work on this. I will do the method we discussed and [as above mentioned](https://github.com/PrestigeDAO/prestige-program/issues/3#issuecomment-1222625501).

**Comment by jpcaulfi** [comment]
Let it rip. We may have to simulate the DAO's authority for now, but go ahead and implement the failsafe
